# Generated by Django 2.2.2 on 2019-07-12 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habitats', '0018_habitat_town'),
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistanceHabitatToPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField(verbose_name='فاصله (کیلومتر)')),
                ('habitat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitats.Habitat', verbose_name='اقامتگاه')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Place', verbose_name='مکان گردشگری')),
            ],
        ),
    ]
