# Generated by Django 2.2.2 on 2019-07-13 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190608_0748'),
        ('places', '0002_distancehabitattoplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Member', verbose_name='سازندهٔ مکان'),
        ),
    ]
