# Generated by Django 2.2.2 on 2019-06-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190519_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_habitat_owner',
            field=models.BooleanField(default=False, null=True, verbose_name='صاحب اقامت\u200cگاه؟'),
        ),
    ]
