# Generated by Django 2.2.1 on 2019-06-05 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('habitats', '0002_auto_20190526_0412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitat',
            name='cost',
        ),
        migrations.AddField(
            model_name='habitat',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Member'),
        ),
    ]
