# Generated by Django 2.2.1 on 2019-06-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitats', '0003_auto_20190605_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(default='عادی', max_length=200)),
                ('capacity_in_person', models.PositiveIntegerField(default=0)),
                ('cost_per_night', models.PositiveIntegerField(default=0)),
                ('has_breakfast', models.BooleanField(default=False)),
                ('has_telephone', models.BooleanField(default=False)),
                ('has_wifi', models.BooleanField(default=False)),
                ('has_minibar', models.BooleanField(default=False)),
                ('has_foreign_wc', models.BooleanField(default=False)),
                ('has_bath_tub', models.BooleanField(default=False)),
                ('has_shower', models.BooleanField(default=False)),
                ('has_wc', models.BooleanField(default=False)),
                ('details', models.CharField(max_length=10000, null=True)),
            ],
        ),
    ]
