# Generated by Django 2.2.2 on 2019-06-08 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitats', '0008_auto_20190608_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='room_types/', verbose_name='تصویر'),
        ),
    ]
