# Generated by Django 2.2.2 on 2019-07-01 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habitats', '0010_auto_20190701_2212'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
