# Generated by Django 2.2.2 on 2019-07-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitats', '0012_auto_20190702_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomoutofservice',
            name='number_of_affected_rooms',
            field=models.PositiveIntegerField(default=1, verbose_name='تعداد اتاق\u200cها'),
        ),
    ]
