# Generated by Django 2.2.2 on 2019-07-03 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habitats', '0013_roomoutofservice_number_of_affected_rooms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomoutofservice',
            old_name='inclusive_until',
            new_name='exclusive_until',
        ),
    ]
