# Generated by Django 2.2.2 on 2019-07-05 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habitats', '0014_auto_20190703_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeographicDivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_city', models.BooleanField()),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='habitats.GeographicDivision')),
            ],
        ),
    ]
