# Generated by Django 2.2.2 on 2019-07-05 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habitats', '0015_geographicdivision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geographicdivision',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habitats.GeographicDivision'),
        ),
    ]
