# Generated by Django 2.2.2 on 2019-07-05 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habitats', '0016_auto_20190705_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitat',
            name='town',
        ),
    ]
