# Generated by Django 2.2.2 on 2019-07-05 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habitats', '0017_remove_habitat_town'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitat',
            name='town',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='habitats.GeographicDivision', verbose_name='شهر'),
        ),
    ]
