# Generated by Django 2.2.2 on 2019-06-06 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='زمان تغییر')),
                ('amount', models.PositiveIntegerField(verbose_name='مبلغ')),
                ('verified', models.BooleanField(default=False, verbose_name='انجام شده')),
                ('from_user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_transactions', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
