# Generated by Django 2.2.2 on 2019-07-07 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20190706_2336'),
        ('reservation', '0002_reservation_transaction'),
    ]

    operations = [
    ]
