# Generated by Django 2.2.2 on 2019-07-15 05:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20190706_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='rating',
        ),
        migrations.CreateModel(
            name='ReservationComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز')),
                ('review', models.TextField(null=True, verbose_name='متن نظر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت نظر')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='reservation.Reservation', verbose_name='رزرو')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceCommentVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='reservation_comments/videos/')),
                ('reservation_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='reservation.ReservationComment', verbose_name='نظر')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceCommentPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='reservation_comments/photos/', verbose_name='تصویر')),
                ('reservation_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='reservation.ReservationComment', verbose_name='نظر')),
            ],
        ),
    ]
