# Generated by Django 2.2.2 on 2019-07-15 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_auto_20190715_0954'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlaceCommentPhoto',
            new_name='ReservationCommentPhoto',
        ),
        migrations.RenameModel(
            old_name='PlaceCommentVideo',
            new_name='ReservationCommentVideo',
        ),
    ]
