# Generated by Django 2.2.2 on 2019-07-16 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_auto_20190716_0355'),
        ('reservation', '0004_auto_20190715_1004'),
    ]

    operations = [
    ]
